import { HANDS_MAX_TREE_NODES, isAccessibilityEnabled, type AccessibilityNode } from '../../../modules/accessibility-agent'
import { nativeFindAccessibilityNodes, nativeGetAccessibilityTree, nativePerformAccessibilityAction } from '../../../modules/accessibility-agent/native'
import { actionSchema, findQuerySchema, type AccessibilityAction } from '../accessibility-tools'

type AccessibilityExecutionResult = { status: string; action: string }
async function getAccessibilityTree(maxNodes = HANDS_MAX_TREE_NODES): Promise<AccessibilityNode[]> { return nativeGetAccessibilityTree(Math.max(1, Math.min(maxNodes, HANDS_MAX_TREE_NODES))) }
async function performAccessibilityAction(action: AccessibilityAction): Promise<AccessibilityExecutionResult> { return nativePerformAccessibilityAction(action) }
export async function executeUiObserve(maxNodes?: number) { const enabled=await isAccessibilityEnabled(); if(!enabled)return {status:'accessibility_disabled',nodes:[] as AccessibilityNode[]}; return {status:'observed',nodes:await getAccessibilityTree(maxNodes)} }
function rootPackage(nodes: AccessibilityNode[]): string|null{return nodes.find(n=>n.id==='0')?.packageName??nodes[0]?.packageName??null}
function stableNode(n: AccessibilityNode){return [n.id,n.text??'',n.contentDescription??'',n.resourceId??'',n.packageName??'',n.bounds.left,n.bounds.top,n.bounds.right,n.bounds.bottom,n.clickable,n.editable,n.enabled].join('\u001f')}
export function computeFingerprint(nodes: AccessibilityNode[]): string { let hash=2166136261; for(const s of nodes.map(stableNode)){for(let i=0;i<s.length;i++){hash^=s.charCodeAt(i);hash=Math.imul(hash,16777619)}} return (hash>>>0).toString(16).padStart(8,'0') }
export function verifyByFingerprintChange(before: AccessibilityNode[],after: AccessibilityNode[]):boolean{return computeFingerprint(before)!==computeFingerprint(after)}
function containsExpectedText(nodes:AccessibilityNode[],expected?:string){if(!expected?.trim())return false;const e=expected.trim();return nodes.some(n=>(n.text??'').trim()===e||(n.contentDescription??'').trim()===e)}
function treeMatchesCausally(before:AccessibilityNode[],after:AccessibilityNode[],expectedText?:string,expectedPackage?:string,verifyStrategy:'ui_tree_change'|'ui_target_state'|'system_state_change'='ui_target_state'){if(expectedPackage&&rootPackage(after)!==expectedPackage)return false;if(verifyStrategy==='system_state_change')return true;if(expectedText&&!containsExpectedText(after,expectedText))return false;if(expectedText&&containsExpectedText(before,expectedText)&&!expectedPackage)return verifyStrategy==='ui_tree_change'&&verifyByFingerprintChange(before,after);if(expectedPackage&&rootPackage(before)===expectedPackage&&!expectedText)return verifyStrategy==='ui_tree_change'&&verifyByFingerprintChange(before,after);if(!expectedText&&!expectedPackage)return verifyByFingerprintChange(before,after);return true}
export async function executeUiAction(input:{action:unknown;waitMs:number;expectedText?:string;expectedPackage?:string;verifyStrategy?:'ui_tree_change'|'ui_target_state'|'system_state_change'}){const action=actionSchema.parse(input.action);if(!(await isAccessibilityEnabled()))return{status:'accessibility_disabled',action:action.type,verified:false};const before=await getAccessibilityTree();const result=await performAccessibilityAction(action);if(result.status!=='executed')return{...result,verified:false,before,after:before};await new Promise(r=>setTimeout(r,input.waitMs));const after=await getAccessibilityTree();const verified=treeMatchesCausally(before,after,input.expectedText,input.expectedPackage,input.verifyStrategy??'ui_target_state');return{status:verified?'verified':'executed_unverified',action:action.type,verified,before,after,beforeFingerprint:computeFingerprint(before),afterFingerprint:computeFingerprint(after)}}
export async function executeFindNodes(query:unknown){const parsed=findQuerySchema.parse(query);if(!(await isAccessibilityEnabled()))return{status:'accessibility_disabled',results:[]};return{status:'found',results:await nativeFindAccessibilityNodes(parsed)}}
