import { HANDS_ACTIONS, HandsActionType, HandsRisk, actionPolicy } from './action-model';

export type HandsAvailabilityStatus = 'implemented' | 'stub' | 'blocked' | 'unavailable';
export type HandsPostconditionStrategy =
  | 'ui_tree_change' | 'ui_target_state' | 'intent_launched' | 'system_state_change'
  | 'file_exists' | 'file_state_change' | 'telecom_event' | 'media_state_change'
  | 'observation_only' | 'custom_evidence';

export interface HandsCapabilitySpec {
  type: HandsActionType;
  executorId: string | null;
  requiredPermissions: readonly string[];
  riskLevel: HandsRisk;
  requiresApproval: boolean;
  timeoutMs: number;
  retryPolicy: { maxAttempts: number; reobserveBeforeRetry: boolean };
  postconditionStrategy: HandsPostconditionStrategy;
  auditEventType: string;
  availabilityStatus: HandsAvailabilityStatus;
}

const defaults: Record<HandsActionType, Omit<HandsCapabilitySpec, 'type'>> = {
  launch_app: { executorId: 'android.intent.launch_app', requiredPermissions: [], riskLevel: actionPolicy('launch_app').risk, requiresApproval: false, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.launch_app', availabilityStatus: 'implemented' },
  open_url: { executorId: 'android.intent.open_url', requiredPermissions: [], riskLevel: actionPolicy('open_url').risk, requiresApproval: false, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.open_url', availabilityStatus: 'implemented' },
  tap: { executorId: 'accessibility.tap', requiredPermissions: [], riskLevel: actionPolicy('tap').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.tap', availabilityStatus: 'implemented' },
  double_tap: { executorId: 'accessibility.double_tap', requiredPermissions: [], riskLevel: actionPolicy('double_tap').risk, requiresApproval: false, timeoutMs: 6000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.double_tap', availabilityStatus: 'implemented' },
  long_press: { executorId: 'accessibility.long_press', requiredPermissions: [], riskLevel: actionPolicy('long_press').risk, requiresApproval: false, timeoutMs: 6000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.long_press', availabilityStatus: 'implemented' },
  swipe: { executorId: 'accessibility.swipe', requiredPermissions: [], riskLevel: actionPolicy('swipe').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_tree_change', auditEventType: 'hands.swipe', availabilityStatus: 'implemented' },
  drag: { executorId: 'accessibility.drag', requiredPermissions: [], riskLevel: actionPolicy('drag').risk, requiresApproval: false, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.drag', availabilityStatus: 'implemented' },
  type_text: { executorId: 'accessibility.type_text', requiredPermissions: [], riskLevel: actionPolicy('type_text').risk, requiresApproval: true, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.type_text', availabilityStatus: 'implemented' },
  clear_text: { executorId: 'accessibility.clear_text', requiredPermissions: [], riskLevel: actionPolicy('clear_text').risk, requiresApproval: true, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.clear_text', availabilityStatus: 'implemented' },
  select_text: { executorId: 'accessibility.select_text', requiredPermissions: [], riskLevel: actionPolicy('select_text').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.select_text', availabilityStatus: 'implemented' },
  copy: { executorId: 'accessibility.copy', requiredPermissions: [], riskLevel: actionPolicy('copy').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'system_state_change', auditEventType: 'hands.copy', availabilityStatus: 'implemented' },
  paste: { executorId: 'accessibility.paste', requiredPermissions: [], riskLevel: actionPolicy('paste').risk, requiresApproval: true, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_target_state', auditEventType: 'hands.paste', availabilityStatus: 'implemented' },
  scroll: { executorId: 'accessibility.scroll', requiredPermissions: [], riskLevel: actionPolicy('scroll').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_tree_change', auditEventType: 'hands.scroll', availabilityStatus: 'implemented' },
  back: { executorId: 'accessibility.back', requiredPermissions: [], riskLevel: actionPolicy('back').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_tree_change', auditEventType: 'hands.back', availabilityStatus: 'implemented' },
  home: { executorId: 'accessibility.home', requiredPermissions: [], riskLevel: actionPolicy('home').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_tree_change', auditEventType: 'hands.home', availabilityStatus: 'implemented' },
  recents: { executorId: 'accessibility.recents', requiredPermissions: [], riskLevel: actionPolicy('recents').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'ui_tree_change', auditEventType: 'hands.recents', availabilityStatus: 'implemented' },
  wait: { executorId: 'runtime.wait', requiredPermissions: [], riskLevel: actionPolicy('wait').risk, requiresApproval: false, timeoutMs: 30000, retryPolicy: { maxAttempts: 1, reobserveBeforeRetry: false }, postconditionStrategy: 'observation_only', auditEventType: 'hands.wait', availabilityStatus: 'implemented' },
  read_screen: { executorId: 'accessibility.read_screen', requiredPermissions: [], riskLevel: actionPolicy('read_screen').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'observation_only', auditEventType: 'hands.read_screen', availabilityStatus: 'implemented' },
  screenshot: { executorId: 'android.screenshot', requiredPermissions: [], riskLevel: actionPolicy('screenshot').risk, requiresApproval: false, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'custom_evidence', auditEventType: 'hands.screenshot', availabilityStatus: 'implemented' },
  find_text: { executorId: 'accessibility.find_text', requiredPermissions: [], riskLevel: actionPolicy('find_text').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'observation_only', auditEventType: 'hands.find_text', availabilityStatus: 'implemented' },
  find_element: { executorId: 'accessibility.find_element', requiredPermissions: [], riskLevel: actionPolicy('find_element').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'observation_only', auditEventType: 'hands.find_element', availabilityStatus: 'implemented' },
  press_key: { executorId: 'accessibility.press_global_action', requiredPermissions: [], riskLevel: actionPolicy('press_key').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'system_state_change', auditEventType: 'hands.press_key', availabilityStatus: 'implemented' },
  set_volume: { executorId: 'android.audio.volume', requiredPermissions: [], riskLevel: actionPolicy('set_volume').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'system_state_change', auditEventType: 'hands.set_volume', availabilityStatus: 'implemented' },
  set_brightness: { executorId: 'android.display.brightness', requiredPermissions: ['android.permission.WRITE_SETTINGS'], riskLevel: actionPolicy('set_brightness').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'system_state_change', auditEventType: 'hands.set_brightness', availabilityStatus: 'implemented' },
  toggle_flashlight: { executorId: 'android.camera.flashlight', requiredPermissions: [], riskLevel: actionPolicy('toggle_flashlight').risk, requiresApproval: false, timeoutMs: 5000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'system_state_change', auditEventType: 'hands.toggle_flashlight', availabilityStatus: 'implemented' },
  open_settings: { executorId: 'android.intent.settings', requiredPermissions: [], riskLevel: actionPolicy('open_settings').risk, requiresApproval: false, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.open_settings', availabilityStatus: 'implemented' },
  set_alarm: { executorId: 'android.intent.alarm', requiredPermissions: [], riskLevel: actionPolicy('set_alarm').risk, requiresApproval: true, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.set_alarm', availabilityStatus: 'implemented' },
  create_calendar_event: { executorId: 'android.calendar', requiredPermissions: ['android.permission.WRITE_CALENDAR'], riskLevel: actionPolicy('create_calendar_event').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.create_calendar_event', availabilityStatus: 'implemented' },
  call: { executorId: 'android.telecom.call', requiredPermissions: ['android.permission.CALL_PHONE'], riskLevel: actionPolicy('call').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'telecom_event', auditEventType: 'hands.call', availabilityStatus: 'implemented' },
  send_sms: { executorId: 'android.telephony.sms', requiredPermissions: ['android.permission.SEND_SMS'], riskLevel: actionPolicy('send_sms').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'telecom_event', auditEventType: 'hands.send_sms', availabilityStatus: 'implemented' },
  send_message: { executorId: 'android.intent.message', requiredPermissions: [], riskLevel: actionPolicy('send_message').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'telecom_event', auditEventType: 'hands.send_message', availabilityStatus: 'implemented' },
  share: { executorId: 'android.intent.share', requiredPermissions: [], riskLevel: actionPolicy('share').risk, requiresApproval: true, timeoutMs: 10000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'intent_launched', auditEventType: 'hands.share', availabilityStatus: 'implemented' },
  file_read: { executorId: 'android.saf.read', requiredPermissions: [], riskLevel: actionPolicy('file_read').risk, requiresApproval: false, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'file_exists', auditEventType: 'hands.file_read', availabilityStatus: 'implemented' },
  file_write: { executorId: 'android.saf.write', requiredPermissions: [], riskLevel: actionPolicy('file_write').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'file_state_change', auditEventType: 'hands.file_write', availabilityStatus: 'implemented' },
  file_move: { executorId: 'android.saf.move', requiredPermissions: [], riskLevel: actionPolicy('file_move').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'file_state_change', auditEventType: 'hands.file_move', availabilityStatus: 'implemented' },
  file_delete: { executorId: 'android.saf.delete', requiredPermissions: [], riskLevel: actionPolicy('file_delete').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'file_state_change', auditEventType: 'hands.file_delete', availabilityStatus: 'implemented' },
  file_rename: { executorId: 'android.saf.rename', requiredPermissions: [], riskLevel: actionPolicy('file_rename').risk, requiresApproval: true, timeoutMs: 15000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'file_state_change', auditEventType: 'hands.file_rename', availabilityStatus: 'implemented' },
  camera: { executorId: 'android.camera', requiredPermissions: [], riskLevel: actionPolicy('camera').risk, requiresApproval: true, timeoutMs: 20000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'custom_evidence', auditEventType: 'hands.camera', availabilityStatus: 'implemented' },
  play_media: { executorId: 'android.media.play', requiredPermissions: [], riskLevel: actionPolicy('play_media').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'media_state_change', auditEventType: 'hands.play_media', availabilityStatus: 'implemented' },
  pause_media: { executorId: 'android.media.pause', requiredPermissions: [], riskLevel: actionPolicy('pause_media').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'media_state_change', auditEventType: 'hands.pause_media', availabilityStatus: 'implemented' },
  next_media: { executorId: 'android.media.next', requiredPermissions: [], riskLevel: actionPolicy('next_media').risk, requiresApproval: false, timeoutMs: 8000, retryPolicy: { maxAttempts: 2, reobserveBeforeRetry: true }, postconditionStrategy: 'media_state_change', auditEventType: 'hands.next_media', availabilityStatus: 'implemented' },
  custom_tool: { executorId: null, requiredPermissions: [], riskLevel: actionPolicy('custom_tool').risk, requiresApproval: true, timeoutMs: 30000, retryPolicy: { maxAttempts: 1, reobserveBeforeRetry: true }, postconditionStrategy: 'custom_evidence', auditEventType: 'hands.custom_tool', availabilityStatus: 'blocked' },
};

export const HANDS_CAPABILITIES: readonly HandsCapabilitySpec[] = HANDS_ACTIONS.map(type => ({ type, ...defaults[type] }));
export const HANDS_CAPABILITY_COUNT = HANDS_CAPABILITIES.length;

export function getHandsCapability(type: HandsActionType): HandsCapabilitySpec { return defaults[type] ? { type, ...defaults[type] } : (() => { throw new Error(`Unknown Hands capability: ${type}`); })(); }

/** Registry invariant: every vocabulary entry has exactly one metadata entry. */
export function assertHandsRegistryComplete(): void {
  if (HANDS_CAPABILITIES.length !== HANDS_ACTIONS.length) throw new Error(`Hands registry mismatch: ${HANDS_CAPABILITIES.length} != ${HANDS_ACTIONS.length}`);
  const seen = new Set(HANDS_CAPABILITIES.map(c => c.type));
  if (seen.size !== HANDS_ACTIONS.length) throw new Error('Hands registry contains duplicate capabilities');
}
assertHandsRegistryComplete();
